### ISSUE TITLE
Wrap it up

### ISSUE THREAD

**Issue by tmorris24** [Escapes-today/Escapes.today#28]
Still need to:

~~Fix links~~
~~Finish Footer~~ As done as its gonna be for now
~~Create Contacts Page~~
~~Create Travel Tips Page~~
Add one more Package for each page
~~Fix Weather~~
Change package images
~~Add Italy Packages and Alt tags.~~

**Comment by clayton13** [comment]
This was for regionals. Opening new issue with tasks.
