### ISSUE TITLE
Cart system improvements

### ISSUE THREAD

**Issue by tmorris24** [Escapes-today/Escapes.today#34]
We really only need two more major additions to the system for it to be finished.

Hotel interactivity in the cart system (or something similar)
Dialog boxes

**Comment by clayton13** [comment]
I didn't have time to change the CSS to allow interactivity in the travel plan. I will try to do this tonight after we fix up the rest of the site.

I added dialog boxes for all the alert() and confirm() dialogs we had previously.

**Comment by clayton13** [comment]
Improved finalize dialog and created a dialog to deal with an empty cart.
